export const data = [
    {
      name: "Umbrella(feat Jay Z)",
      song : "http://localhost:1337/uploads/Rihanna_Umbrella_Ft_Jay_Z_320_f8ee859d4b.mp3" ,
      cover : "" ,
      artist : 'Rihanna' ,
    },
    {
        name: "Under The Influence",
        song : "http://localhost:1337/uploads/Chris_Brown_Under_the_Influence_f135a80eec.mp3" ,
        cover : "" ,
        artist : 'Chris Brown' ,
    },
    {
        name: "Leaving Heaven(feat Skylar Grey)",
        song : "http://localhost:1337/uploads/Eminem_Leaving_Heaven_Ft_Skylar_Grey_320_74cf46542a.mp3" ,
        cover : "" ,
        artist : 'Eminem' ,
    },
    {
        name: "The Monster(feat Rihanna)",
        song : "http://localhost:1337/uploads/Eminem_The_Monster_Ft_Rihanna_320_3998f3c647.mp3" ,
        cover : "" ,
        artist : 'Eminem' ,
    },
    {
        name: "Venom",
        song : "http://localhost:1337/uploads/Eminem_Venom_Music_From_The_Motion_Picture_320_b745409b8f.mp3" ,
        cover : "" ,
        artist : 'Eminem' ,
    },
    {
        name: "City of Gods",
        song : "http://localhost:1337/uploads/Fivio_Foreign_Kanye_West_Alicia_Keys_City_of_Gods_320_f33a920f4c.mp3" ,
        cover : "" ,
        artist : 'Kanye West' ,
    },
    {
        name: "Mask Off(feat Kendrick Lamar)",
        song : "http://localhost:1337/uploads/Future_Mask_Off_Remix_Ft_Kendrick_Lamar_320_9f2b8903c9.mp3" ,
        cover : "" ,
        artist : 'Future' ,
    },
    {
        name: "GOOBA",
        song : "http://localhost:1337/uploads/Gooba_69_e8c3ea40d2.mp3" ,
        cover : "" ,
        artist : '6ix9ine' ,
    },
    {
        name: "New Americana",
        song : "http://localhost:1337/uploads/Halsey_New_Americana_320_48f85cf3a3.mp3" ,
        cover : "" ,
        artist : 'Halsey' ,
    },
    {
        name: "Believer",
        song : "http://localhost:1337/uploads/Imagine_Dragons_Believer_320_d530b4a5f1.mp3" ,
        cover : "" ,
        artist : 'Imagine Dragons' ,
    },
    {
        name: "Humble",
        song : "http://localhost:1337/uploads/Kendrick_Lamar_Humble_320_320b381db0.mp3" ,
        cover : "" ,
        artist : 'Kendrick Lamar' ,
    },
    {
        name: "Bloody Mary",
        song : "http://localhost:1337/uploads/Lady_Gaga_Bloody_Mary_320_a0fc7ab6ef.mp3" ,
        cover : "" ,
        artist : 'Lady Gaga' ,
    },
    {
        name: "Dan Dan(feat Moody Moussavi)",
        song : "http://localhost:1337/uploads/Mehrad_Hidden_Dan_Dan_Ft_Moody_Moussavi_320_cf631c7725.mp3" ,
        cover : "" ,
        artist : 'Mehrad Hidden' ,
    },
    {
        name: "Tkouh Taka(feat Nicki Minaj , Maluma)",
        song : "http://localhost:1337/uploads/Nicki_Minaj_Maluma_Myriam_Fares_Tukoh_Taka_320_56c0f1a737.mp3" ,
        cover : "" ,
        artist : 'Myriam Fares' ,
    },
    {
        name: "Circles",
        song : "http://localhost:1337/uploads/Post_Malone_Circles_320_e98452ef66.mp3" ,
        cover : "" ,
        artist : 'Post Malone' ,
    },
    {
        name: "Sun Flower(feat Swae Lee)",
        song : "http://localhost:1337/uploads/Post_Malone_Swae_Lee_Sunflower_Spider_Man_Into_the_Spider_c6ac8e3611.mp3" ,
        cover : "" ,
        artist : 'Post Malone' ,
    },
    {
        name: "Wow",
        song : "http://localhost:1337/uploads/Post_Malone_Wow_320_b69e4de535.mp3" ,
        cover : "" ,
        artist : 'Post Malone' ,
    },
    {
        name: "Nagi Jaei",
        song : "http://localhost:1337/uploads/Purya_Putak_Nagi_Jaei_320_2880eed802.mp3" ,
        cover : "" ,
        artist : 'Putak' ,
    },
    {
        name: "Stay(feat Mikky Ekko)",
        song : "http://localhost:1337/uploads/Rihanna_Stay_Ft_Mikky_Ekko_320_021b9a360e.mp3" ,
        cover : "" ,
        artist : 'Rihanna' ,
    },
    {
        name: "Chandelier",
        song : "http://localhost:1337/uploads/Sia_Chandelier_320_b854fb812f.mp3" ,
        cover : "" ,
        artist : 'Sia' ,
    },
  ]